// Emit the resolved suffix registry as portable JSON, for consumers that are
// not TypeScript (or not JavaScript at all). The TypeScript in src/ is the
// authored source; this file is generated, and `pnpm build` regenerates it.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const { suffixes } = await import('../dist/index.js');

const out = {
  $comment:
    'GENERATED by scripts/emit-json.mjs — do not edit. Source of truth: ' +
    'skills/mongol-bichig/references/suffixes.md (normative prose) compiled ' +
    'through src/data/suffixes.ts. Regenerate with `pnpm build`.',
  entries: suffixes.map((entry) => ({
    ...entry,
    codepoints: [...entry.sequence].map(
      (ch) => `U+${ch.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')}`,
    ),
  })),
};

const path = fileURLToPath(new URL('../data/suffixes.json', import.meta.url));
writeFileSync(path, `${JSON.stringify(out, null, 2)}\n`);
process.stdout.write(`wrote ${out.entries.length} entries to data/suffixes.json\n`);
